name: Install repository
description: Install the repository dependencies

runs:
  using: composite

  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
        registry-url: 'https://registry.npmjs.org'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
