name: Install repository

runs:
  using: composite

  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
