name: Hardhat

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Hardhat unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/install
      - name: Build contracts
        run: yarn compile:hardhat --force # don't use compilation cache
      - name: Run hardhat tests
        run: yarn test:hardhat
