# Simple workflow for deploying static content to GitHub Pages
name: Report Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    # branches: master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Build Coverage Report
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Install genhtml
        run: sudo apt-get install lcov
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # build hardhat coverage
      - name: Build hardhat contracts
        run: yarn compile:hardhat --force # don't use compilation cache
      - name: Check hardhat coverage
        run: yarn coverage:hardhat

      # build foundry coverage
      - name: Build foundry contracts
        run: yarn compile:forge # don't use compilation cache
      - name: Check foundry coverage
        run: yarn coverage:forge && genhtml ./lcov.info --output-dir coverage/foundry --branch-coverage  --ignore-errors inconsistent

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only report folder
          path: './coverage'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
