# Simple workflow for deploying static content to GitHub Pages
name: Report Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    # branches: master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Build Coverage Report
    steps:
      # setup env
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install lcov
        run: sudo apt-get -y install lcov
        shell: bash
      - uses: ./.github/actions/install
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Run foundry coverage
        run: yarn compile:forge && yarn coverage:forge
        #  && genhtml ./lcov.info --output-dir coverage/foundry --branch-coverage  --ignore-errors inconsistent
      - name: Report code coverage
        run: genhtml lcov.info --output-dir coverage/foundry --rc lcov_branch_coverage=1
        shell: bash

      - name: Run hardhat coverage
        run: yarn compile:hardhat --force && yarn coverage:hardhat

      # Deploy to gh pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './coverage'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
