name: Report Gas

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Report Gas Usage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/install
      - name: Build contracts
        run: yarn compile:hardhat --force # don't use compilation cache
      - name: Run hardhat tests with gas report
        run: REPORT_GAS=true npx hardhat test
